name: deploy-app

on:
  push:
    paths:
      - "apps/app/**"
      - "packages/ui/**"
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages - App
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build dist bundle
        run: pnpm build:app
      - name: Deploy: App
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'gc-app' # e.g. 'my-project'
          directory: 'apps/app/dist' # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
