name: deploy-app

on:
  push:
    paths:
      - "apps/app/**"
      - "packages/ui/**"
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages - App
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build dist bundle
        run: pnpm build:app
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          wranglerVersion: "3"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/app"
          command: pages deploy dist --project-name=gc-app
          packageManager: "pnpm"
