name: deploy-app

on:
  push:
    paths:
      - "apps/app/**"
      - "packages/ui/**"
      - .github/workflows/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages - App
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build dist bundle
        run: pnpm build:app
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/app
          command: pages deploy dist --project-name=gc-app
          packageManager: pnpm
