name: deploy-api

on:
  push:
    paths:
      - "apps/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers - API
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3"
          apiToken: ${{ secrets.GAZA_CARE_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.GAZA_CARE_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/api"
          command: deploy -e production --minify src/index.ts
          packageManager: "pnpm"
