name: deploy-medic

on:
  push:
    paths:
      - "apps/medic/**"
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages - Medic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build dist bundle
        env:
          VITE_API_URI: ${{ vars.API_URI }}
          VITE_GOOGLE_API_CLIENT_ID: ${{ vars.GOOGLE_API_CLIENT_ID }}
        run: pnpm build:medic
      - name: Deploy
        id: wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3"
          apiToken: ${{ secrets.GAZA_CARE_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.GAZA_CARE_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/medic"
          command: pages deploy dist --project-name=medic
          packageManager: "pnpm"
      - name: Generate summary
        run: |
          echo "### Preview URL: ${{ steps.wrangler.outputs.deployment-url }}" >> $GITHUB_STEP_SUMMARY
