name: deploy-admin

on:
  push:
    paths:
      - "apps/admin/**"
      - "packages/ui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages - Admin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build dist bundle
        run: pnpm build:admin
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/admin"
          command: pages deploy dist --project-name=gc-admin
          packageManager: "pnpm"
